# Generated by Django 5.0.6 on 2024-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=100)),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
